FROM node:14.17.3 AS base
FROM base AS build

WORKDIR /app

COPY package.json .

COPY package-lock.json .

COPY .npmrc .

ARG CI

RUN npm --quiet ci

COPY . .

RUN npm run install-client
RUN npm run lint
RUN npm run build-client
RUN npm run build-server
